### PR TITLE
- change iOS target to 10

### PR DESCRIPTION
**Pull request by MonikaSarota**
- change swift version 4.2

### CODE REVIEW

**Review by filipealva — APPROVED** [review]
It's looking great! Thank you, @MonikaSarota 👍

**Comment by Ariandr** [comment]
@filipealva @MonikaSarota  Hello. I have a question. You can leave the target version at least to be 9.0, not 10.0, can't you?

A lot of projects using this pod have minimal deployment target 9.0 and I think if it's possible to leave at least 9.0 instead of 10.0, it's better to leave. Or is there an apparent reason to support only 10.0 and higher, some blocking issues?

**Comment by filipealva** [comment]
@Ariandr Hey, thanks for bringing it up. I just get it back to iOS 8 on #49 since it doesn't cause any issue for the newer iOS versions.

**Comment by Ariandr** [comment]
@filipealva Great, thank you!

**Pull request merged**
